
export const GET_AUTH_USER_START = 'GET_AUTH_USER_START';
export const GET_AUTH_USER_SUCCESS = 'GET_AUTH_USER_SUCCESS';
export const GET_AUTH_USER_FAILURE = 'GET_AUTH_USER_FAILURE';

export const SET_JOB_POST_APPOINTMENT = 'SET_JOB_POST_APPOINTMENT'
export const SET_JOB_POST_APPOINTMENT_SHIFT = 'SET_JOB_POST_APPOINTMENT_SHIFT'

export const SET_JOB_POST_CATEGORY = 'SET_JOB_POST_CATEGORY';
export const SET_JOB_POST_SUBCATEGORY = 'SET_JOB_POST_SUBCATEGORY';
export const SET_JOB_POST_TIME = 'SET_JOB_POST_TIME';
export const SET_JOB_POST_DATE = 'SET_JOB_POST_DATE';
export const SET_JOB_POST_AGE = 'SET_JOB_POST_AGE';
export const SET_JOB_POST_LOCATION = 'SET_JOB_POST_LOCATION';
export const SET_JOB_POST_CONTACT_DETAIL = 'SET_JOB_POST_CONTACT_DETAIL';
export const JOB_POST_REFRESH = 'JOB_POST_REFRESH';

export const SET_JOB_POST_SHOW_MAP = 'SET_JOB_POST_SHOW_MAP';
export const SET_JOB_POST_ERROR = 'SET_JOB_POST_ERROR';

export const GET_OFFERS_START = 'GET_OFFERS_START'
export const GET_OFFERS_SUCCESS = 'GET_OFFERS_SUCCESS'
export const GET_OFFERS_FAILURE = 'GET_OFFERS_FAILURE'
